# compose.yaml
services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    restart: always
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB2_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB2_BUCKET}
    secrets:
      - influxdb2-admin-token
      - influxdb2-admin-password
      - influxdb2-admin-username
    volumes:
      - ./influxdb2-data:/var/lib/influxdb2
      - ./influxdb2-config:/etc/influxdb2
    networks:
      - influxdb2-network
  
  price-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price-tracker
    restart: always
    ports:
      - 3020:3020
    depends_on:
      - influxdb2
    environment:
      INFLUXDB2_HOST: ${INFLUXDB2_HOST}
      INFLUXDB2_PORT: ${INFLUXDB2_PORT}
      INFLUXDB2_ORG: ${INFLUXDB2_ORG}
      INFLUXDB2_BUCKET: ${INFLUXDB2_BUCKET}
      INFLUXDB2_ADMIN_TOKEN: /run/secrets/influxdb2-admin-token
    secrets:
      - influxdb2-admin-token
    networks:
      - influxdb2-network

networks:
  influxdb2-network:
    name: influxdb2-network
    driver: bridge

secrets:
  influxdb2-admin-token:
    external: true
  influxdb2-admin-password:
    external: true
  influxdb2-admin-username:
    external: true